# Generated by Django 4.2.3 on 2023-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
