# Generated by Django 4.2.3 on 2023-07-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_last_name_record_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='Last_name',
        ),
    ]
